= OASP4JS Angular 2 web application supporting the process of cooking meals

The application supports the meal cooking process,
optimize the time needed to prepare and reduce the costs of preparing meals. With the application, the cooking process will be easier and will bring satisfaction to the user. The system provides two types of users: simple users and logged.
 
Functionals:
* Possibility to search for meals by name
* Ability to search for meals according to criteria (budget, preparation time, ingredients, type of dishes)
* Ability to view recipe details
* Adding a new meal

== Getting Started

=== Installing back-end of web application supporting the process of cooking meals

All information of how to install and run back-end for our apllication is on https://github.com/dmytro-martyniuk/ZPI.
Befor running this aplication install and run back-end of web application supporting the process of cooking meals

=== Install prerequisites

You need a Git client, the https://nodejs.org/[Node.js] platform (including its package manager - https://www.npmjs.com/[npm]) and http://gulpjs.com/[Gulp] to make use of the project seed.
It is highly recommended to use the following versions:

* Node.js 5.12.0
* npm 3.3.6
* Gulp 3.9.1

Please refer to the link:#prerequisites[FAQ section] for details on how to install the prerequisites.

=== Install the OASP4JS Angular 2 web application supporting the process of cooking meals

Clone the repository:

....
git clone https://github.com/Wolodja/Kuchnia-Front.git
....

Install all node.js dependencies (this may take several minutes when doing for the first time):

....
npm install
....

Start an application:

....
gulp
....

Run tests:

....
gulp test
....


Your default browser opens and shows the application. What is more, you can now develop this application
using your favorite IDE while the Gulp process is watching for your changes and upon them reloads the sample application
automatically in your browser.


== Frequently Asked Questions

=== [[prerequisites]]How to install the prerequisites?

==== Git
Check if you have a Git client already installed:

----
git --version
----

If your OS can not recognize this command, install Git. For details please refer to http://git-scm.com[this page].
When installing under Windows, please make sure you check the following option:

- [*] Use git from Windows command prompt

==== Node.js

It is highly recommended to install the  https://github.com/creationix/nvm[Node Version Manager] which manages multiple active
Node.js versions on your machine. The windows version of nvm can be found https://github.com/coreybutler/nvm-windows#installation--upgrades[here].

==== Gulp

http://gulpjs.com/[Gulp] is a streaming build system. Install the Gulp globally using the npm. Type the following command in the command line tool:

----
npm install -g gulp
----

In order to check if Gulp was correctly installed you can check its version by typing:

----
gulp --version
----

'''

=== How to add a new JavaScript library?

As is the case in the https://github.com/angular/quickstart[Angular 2 Quick Start], this project seed uses
npm for dependency management and https://github.com/systemjs/systemjs[SystemJS] for module loading.

Let us assume you would like to add a very popular JavaScript utility library - https://lodash.com/[lodash]. First
install it using npm:

----
npm install lodash --save
----

The above command downloads the library to your `node_modules` directory and updates the `package.json` file.

Second, let SystemJS know that the library can be imported in your TypeScript files; add this to the `systemjs.config.json` file:

[source,javascript]
----
map: {
  ...
  'lodash': 'npm:lodash'
}
packages: {
  ...
  'lodash': {
    main: './index.js',
    defaultExtension: 'js'
  }
}
----

Third, import the library in your TypeScript class and use it:

[source,javascript]
----
import * as _ from 'lodash';

export class MyClass {
  myMethod(): void {
    ...
    _.cloneDeep({name: 'John'});
  }
}
----

'''

=== How to replace Bootstrap with Angular Material?

Switch to the `angular-material` branch:

----
git checkout angular-material
----

install npm dependencies:

----
npm install
----

and run the project seed:

----
gulp
----

'''

=== Start with json server

Install json-server

----
npm install -g json-server
----

Start json-server from the project root directory

----
json-server --watch db.json --routes routes.json --port 4050
----
